
services:
  php:
    build: ./docker/php
    volumes:
      - ./app:/var/www/app
    extra_hosts:
      - "host.docker.internal:host-gateway"

  apache:
    build: ./docker/apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www/app
    depends_on:
      - php
