
services:
  php:
    build: ./docker/php
    volumes:
      - ./apps/web:/var/www/web
    extra_hosts:
      - "host.docker.internal:host-gateway"

  apache:
    build: ./docker/apache
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apps/web:/var/www/web
    depends_on:
      - php
